version: '3.7'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
    ports:
      - "8888:8080"
    networks:
      - containernet-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/desktop-udi-302/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/desktop-udi-302/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    networks:
      containernet-network:
        ipv4_address: 172.20.0.10  # IP fixo para o Redis
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - containernet-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
  # redis:
  #   image: redis
  #   container_name: redis-container
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     containernet-network:
  #       ipv4_address: 172.20.0.10  # IP fixo para o Redis
  #   volumes:
  #     - /home/desktop-udi-302/mqtt-iot-device/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #     - /home/desktop-udi-302/mqtt-iot-device/appendonly:/data
  #   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

networks:
  containernet-network:
    external: true