FROM redis:latest

RUN apt-get update && \
    apt-get install -y net-tools iproute2 ethtool && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./redis/redis.conf /usr/local/etc/redis/redis.conf

VOLUME /data

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]