version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mqtt-device:
    build: .
    container_name: mqtt-device
    depends_on:
      - mosquitto
    environment:
      - BROKER=mosquitto
      - DEVICE_SCRIPT=mqtt_device.py

  http-device:
    build: . 
    container_name: http-device
    depends_on:
      - camel-app
    environment:
      - CAMEL_APP_URL=http://camel-app:8080/api/v1/sensor/data 
      - DEVICE_SCRIPT=http_device.py

  camel-app:
    image: iot-router-backend:latest 
    container_name: camel-app
    depends_on:
      - mosquitto
    ports:
      - "8080:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=dev