# Dockerfile para o Mosquitto com utilitários de rede
FROM eclipse-mosquitto:latest

RUN apk update && apk add --no-cache bash iputils-ping curl net-tools iproute2

CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]