FROM python:3.9-slim

WORKDIR /app

ENV PATH="/usr/sbin:/sbin:${PATH}"

COPY get_container_ips.py /app/get_container_ips.py

RUN pip install --no-cache-dir docker flask redis

RUN apt-get update && apt-get install -y \
    redis-tools \
    iptables \
    stress-ng \
    procps \
    iputils-ping \
    curl \
    net-tools \
    iproute2 \
    mosquitto-clients \
    iperf3 \
    ethtool && \
    rm -rf /var/lib/apt/lists/* 

EXPOSE 5000

CMD ["python", "/app/get_container_ips.py"]