FROM python:3.9-slim

WORKDIR /app

ENV PATH="/usr/sbin:/sbin:${PATH}"

COPY prometheus_api.py /app/prometheus_api.py

RUN pip install --no-cache-dir docker flask prometheus-client

RUN apt-get update && apt-get install -y \
    iptables \
    procps \
    iputils-ping \
    curl \
    net-tools \
    iproute2 \
    iperf3 \
    ethtool && \
    rm -rf /var/lib/apt/lists/* 

EXPOSE 8000

CMD ["python", "/app/prometheus_api.py"]