# Dockerfile para o dispositivo IoT
FROM python:3.9-slim

WORKDIR /app

ENV PATH="/usr/sbin:/sbin:${PATH}"

RUN apt-get update && apt-get install -y procps iputils-ping curl net-tools iproute2 mosquitto-clients iperf3 ethtool

RUN pip install --no-cache-dir --upgrade requests psutil paho-mqtt

COPY temperature.py ./

CMD ["python", "/app/temperature.py"]